**Preamble**

**Colloboration Policy**. The student is to *explicitly identify* his/her collaborators in the assignment. If the student did not work with anyone, he/she should indicate `Collaborators=['none']`. If the student obtains a solution through research (e.g., on the web), acknowledge the source, but *write up the solution in HIS/HER OWN WORDS*. There will be a one mark penalty if a student fails to indicate his/her collaborators.

**There will be NO EXCEPTIONS to this grading policy.**

# Assignment 2 - Sensitivity Analysis

If you need help on using Jupyter notebooks, click <a href='#help'>here</a>. 

Objective:

In this exercise, we perform *sensity analysis* to a specific linear program (LP). 
That is, we analyse the effect of changing parameters on the optimal solution and optimal value.
Specifically, we will look at the following scenarios:

(a) Change in *objective function* for the coefficient of a *nonbasic* variable.

(b) Change in *objective function* for the coefficient of a *basic* variable.

(c) Change in a *RHS* value.

(d) Adding a new *variable*.

(e) Adding a new *constraint*.



# Linear Program LP1

For this assignment, **LP1** refers to the following linear program:

$$
\begin{array}{crcrcrcrl}
\max &   &   & x_2 & - & x_3 & + & x_4\\ 
\text{subject to} 
& x_1 & - &  x_2 & - & 3x_3 & + &  x_4 & \le 7\\ 
&3x_1 & + &  x_2 & + &  x_3 & + & 2x_4 & \le 2\\ 
&6x_1 & + & 2x_2 & + & 3x_3 & - &  x_4 & \le 1\\ 
\end{array}
$$

Note that when we refer to **LP1**. It refers to above problem with **no other modifications**.

In [1]:
# WE COMPUTE THE SOLUTION FOR LP1 HERE

import pulp

model = pulp.LpProblem("LP1", pulp.LpMaximize)

x1 = pulp.LpVariable('x1', lowBound=0)
x2 = pulp.LpVariable('x2', lowBound=0)
x3 = pulp.LpVariable('x3', lowBound=0)
x4 = pulp.LpVariable('x4', lowBound=0)

model += x2-x3+x4, "Z"


model +=   x1 -   x2 - 3*x3 +   x4  <=  7,           "constraint1"
model += 3*x1 +   x2 +   x3  + 2*x4 <=  2,           "constraint2"
model += 6*x1 + 2*x2 + 3*x3 -   x4  <=  1,           "constraint3"

print(model)

model.solve()

print("Z  : {}".format(pulp.value(model.objective)))

print("x1 : {}".format(x1.varValue))
print("x2 : {}".format(x2.varValue))
print("x3 : {}".format(x3.varValue))
print("x4 : {}".format(x4.varValue))


LP1:
MAXIMIZE
1*x2 + -1*x3 + 1*x4 + 0
SUBJECT TO
constraint1: x1 - x2 - 3 x3 + x4 <= 7

constraint2: 3 x1 + x2 + x3 + 2 x4 <= 2

constraint3: 6 x1 + 2 x2 + 3 x3 - x4 <= 1

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous
x4 Continuous

Z  : 1.4
x1 : 0.0
x2 : 0.8
x3 : 0.0
x4 : 0.6


**(0) (5 marks)** Fill in the entries for the *optimal* simplex table.
Show your working. However, feel free to use `numpy` to do the computations (click <a href='#matrix'>here</a> for simple `numpy` matrix operations).

Do take note of the order of the decision variables.

---

*You may use this cell for working.*

In [14]:
# build the slack model 

import pulp

model = pulp.LpProblem("LP1", pulp.LpMaximize)

x1 = pulp.LpVariable('x1', lowBound=0)
x2 = pulp.LpVariable('x2', lowBound=0)
x3 = pulp.LpVariable('x3', lowBound=0)
x4 = pulp.LpVariable('x4', lowBound=0)
u1 = pulp.LpVariable('u1', lowBound=0)
u2 = pulp.LpVariable('u2', lowBound=0)
u3 = pulp.LpVariable('u3', lowBound=0)

model += x2-x3+x4, "Z"


model +=   x1 -   x2 - 3*x3 +   x4  + u1 ==  7,           "constraint1"
model += 3*x1 +   x2 +   x3  + 2*x4 + u2 ==  2,           "constraint2"
model += 6*x1 + 2*x2 + 3*x3 -   x4  + u3 ==  1,           "constraint3"

print(model)

model.solve()

print("Z  : {}".format(pulp.value(model.objective)))

print("x1 : {}".format(x1.varValue))
print("x2 : {}".format(x2.varValue))
print("x3 : {}".format(x3.varValue))
print("x4 : {}".format(x4.varValue))
print("u1 : {}".format(u1.varValue))
print("u2 : {}".format(u2.varValue))
print("u3 : {}".format(u3.varValue))

LP1:
MAXIMIZE
1*x2 + -1*x3 + 1*x4 + 0
SUBJECT TO
constraint1: u1 + x1 - x2 - 3 x3 + x4 = 7

constraint2: u2 + 3 x1 + x2 + x3 + 2 x4 = 2

constraint3: u3 + 6 x1 + 2 x2 + 3 x3 - x4 = 1

VARIABLES
u1 Continuous
u2 Continuous
u3 Continuous
x1 Continuous
x2 Continuous
x3 Continuous
x4 Continuous

Z  : 1.4
x1 : 0.0
x2 : 0.8
x3 : 0.0
x4 : 0.6
u1 : 7.2
u2 : 0.0
u3 : 0.0


*You may use this cell for working.*

In [7]:
#solving the matrix
import numpy as np 

#suppress the decimal digits
np.set_printoptions(precision = 2)

# the BVs are x2, x4, u1
B = np.matrix([
    [-1,  1, 1],
    [ 1,  2, 0],
    [ 2, -1, 0],
])

# the NBVs are x1, x3, u2, u3
N = np.matrix([
    [1, -3, 0, 0],
    [3,  1, 1, 0],
    [6,  3, 0, 1],
])

# first row corresponding to BV, mindful there is a negative sign 
CB = np.matrix([
    [1, 1, 0],
])

#first row corresponding to NBV, mindful there is negative sign
CN = np.matrix([
    [0, -1, 0, 0],
])

#RHS b
b = np.matrix([
    [7],
    [2],
    [1],
])

###############Solving the final optimal table#############
print("\n===Below is for filling up the optimal table")

#solve Inv(B) * N 
Final_N = np.linalg.inv(B)*N
print(Final_N)

#no need solve I, it's just identity matrix
Final_I = np.linalg.inv(B)*B
print(Final_I)

#solve the Inv(B) * b 
Final_b = np.linalg.inv(B)*b
print(Final_b)

#solve the -(CN - CB * Inv(B) * N)
Final_CN = -(CN - CB*(np.linalg.inv(B))*N)
print(Final_CN)

#solve the CB * Inv(B) * b
Final_Z = CB*(np.linalg.inv(B))*b
print(Final_Z)



===Below is for filling up the optimal table
[[ 3.   1.4  0.2  0.4]
 [ 0.  -0.2  0.4 -0.2]
 [ 4.  -1.4 -0.2  0.6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.8]
 [0.6]
 [7.2]]
[[3.  2.2 0.6 0.2]]
[[1.4]]


---

**Answer - Optimal Simplex Table**. Fill in the blanks.

| $Z$ | $x_2$ | $x_4$ | $u_1$ | $x_1$ | $x_3$ | $u_2$ | $u_3$ | RHS |
| :-: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |:---:|
| 1   |   0   |   0   |   0   |   3   |   2.2 |   0.6 |   0.2 | 1.4 |
| 0   |   1   |   0   |   0   |   3   |   1.4 |   0.2 |   0.4 | 0.8 |
| 0   |   0   |   1   |   0   |   0   |  -0.2 |   0.4 |  -0.2 | 0.6 |
| 0   |   0   |   0   |   1   |   4   |  -1.4 |  -0.2 |   0.6 | 7.2 |

---

**(a) (2 marks)**  Consider a new objective function 
$$ c_1x_1 +x_2-x_3+x_4.$$

For what values of $c_1$, will the optimal value remain at $1.4$?


In [8]:
print("=========Below code is for part (a)=========")

Negative_CN = -CN
CB_InvB_N = CB*(np.linalg.inv(B))*N
print(Negative_CN)
print(CB_InvB_N)

=========Below code is for part (a)=========
[[0 1 0 0]]
[[3.  1.2 0.6 0.2]]


---
**Answer to (a)**

NOTE that x1 is NBV, from the source code above, from the code above, we have already found out the following,

**-CN =** (0, 1, 0, 0)

**CB * Inv(B) * N =** (3, 1.2, 0.6, 0.2)

Now, given that we are changing coefficient of x1 from 0 to c1, the first row corresponding to (x1, x3, u2, u3) becomes (3-c1, 2.2, 0.6, 0.2), in order for optimal value to remain at 1.4, 

**-CN + CB * Inv(B) * N = (3-c1, 2.2, 0.6, 0.2)**

3 -c1 >= 0 

**Hence, the answer is c1 <= 3**

---

**(b) (2 marks)**  Consider a new objective function 
$$c_2x_2-x_3+x_4.$$

For what values of $c_2$, will the optimal basis remain unchanged?

In [9]:
print("=========Below code is for part (b)=========")

InvB_N = np.linalg.inv(B)*N
print(Negative_CN)
print(CB)
print(InvB_N)

=========Below code is for part (b)=========
[[0 1 0 0]]
[[1 1 0]]
[[ 3.   1.4  0.2  0.4]
 [ 0.  -0.2  0.4 -0.2]
 [ 4.  -1.4 -0.2  0.6]]


---

**Answer to (b)**

Note that x2 is BV, from the source code above, we have already found out the following

**-CN =** [0 1 0 0]

**Inv(B) * N =**

[ 3.   1.4  0.2  0.4]

 [ 0.  -0.2  0.4 -0.2]

[ 4.  -1.4  -0.2  0.6]

**CB =** [1 1 0]

Now, given that we are changing coefficient of x2 from 1 to c2, CB is now (c2, 1, 0).

**-CN + CB * Inv(B) * N = (3c2, 1.4c2 + 0.8, 0.2c2 + 0.4, 0.4c2 - 0.2)**

The first row corresponding to (x1, x3, u2, u3) becomes (3c2, 1.4c2 + 0.8, 0.2c2 + 0.4, 0.4c2 - 0.2), in order for optimal basis remain unchanged,

3c2 >= 0 (c2 >=0)

1.4c2 + 0.8 >= 0 (c2 >= -4/7)

0.2c2 + 0.4 >= 0 (c2 >= -2)

0.4c2 - 0.2 >= 0 (c2 >= 0.5)

**Hence, the answer is c2 >= 0.5** 



---

**(c) (2 marks)**  Suppose we modify `"constraint 1"` to  
$$ x_1 - x_2 - 3x_3 + x_4 \le b_1.$$

For what values of $b_1$, will the optimal basis remain unchanged?

In [11]:
print("=========Below code is for part (c)=========")
InvB = np.linalg.inv(B)
print(InvB)
print(b)

=========Below code is for part (c)=========
[[ 0.   0.2  0.4]
 [ 0.   0.4 -0.2]
 [ 1.  -0.2  0.6]]
[[7]
 [2]
 [1]]


---

**Answer to (c)**

Note that b1 is RHS, from the source code above, we have already found out the following

**Inv(B) =**

[ 0.   0.2  0.4]

[ 0.   0.4 -0.2]

[ 1.  -0.2  0.6]

**b =**

[7]

[2]

[1]


Now, given that we are changing RHS from (7, 2, 1) to (b1, 2, 1), the new Inv(B) * b becomes

**Inv(B) * b =**  

[0.8]

[0.6]

[b1 + 0.2]


In order for optimail basis to remain unchanged, the following constraints must be satisfied, 

[0.8] >= 0

[0.6] >= 0 

[b1 + 0.2] >= 0

**Hence, the answer is b1 >= -0.2**




---

**(d) (2 marks)** Suppose we add a new variable to **LP1** and the new linear program is:

$$
\begin{array}{crcrcrcrcrl}
\max &   &   & x_2 & - & x_3 & + & x_4 & + &c_5x_5\\ 
\text{subject to} 
& x_1 & - &  x_2 & - & 3x_3 & + &  x_4 & + & x_5 & \le 7\\ 
&3x_1 & + &  x_2 & + &  x_3 & + & 2x_4 & + & x_5 & \le 2\\ 
&6x_1 & + & 2x_2 & + & 3x_3 & - &  x_4 & + & x_5 & \le 1\\ 
\end{array}
$$
For what values of $c_5$, will the optimal value remain unchanged?


In [6]:
print("=========Below code is for part (c)=========")
print(Negative_CN)

N_x5 = np.matrix([
    [1],
    [1],
    [1],
])
#appending the last column of x5 to N
NewN = np.c_[N, N_x5]
CB_InvB_NewN = CB*(np.linalg.inv(B))*NewN
print(NewN)
print(CB_InvB_NewN)

=========Below code is for part (c)=========
[[0 1 0 0]]
[[ 1 -3  0  0  1]
 [ 3  1  1  0  1]
 [ 6  3  0  1  1]]
[[3.  1.2 0.6 0.2 0.8]]


---

**Answer to (d)**

Note that by adding a new variable x5, the N and CN item will be impacted (**New-CN and NewN**). From the source code above, we have already found out the following

**-NewCN =** [0 1 0 0 -c5]

**NewN =**

[ 1 -3  0  0  1]

[ 3  1  1  0  1]

[ 6  3  0  1  1]

**CB_InvB_NewN =** [3.  1.2 0.6 0.2 0.8]

Now, we can get the new first row coefficients corresponding to NBV as(3, 2.2, 0.6. 0.2, 0.8 - c5), 

**-NewCN + CB_InvB_NewN = [3.  2.2 0.6 0.2 0.8 - c5]**

0.8 - c5 >= 0

**Hence, in order for optimal value to remain unchanged, the answer is c5 <= 0.8**

---


**(e) (2 marks)** Suppose we add a new constraint to **LP1** and the new constraint is:

$$
x_1+x_2+x_3+x_4\le b_4
$$
For what values of $b_4$, will the optimal solution remain unchanged?

---

**Answer to (e)**

Since we want the following optimal solution to remain unchanged, 

x1 : 0.0

x2 : 0.8

x3 : 0.0

x4 : 0.6

After introducing slack variable to the new constraint, we have

x1 + x2 + x3 + x4 + u4 = b4 and u4 >= 0

we can get, 

0.0 + 0.8 + 0.0 + 0.6 + u4 = b4

**Hence, as long as b4 >= 1.4, the solution remains unchanged.**

---